acme_pagination_test_homepage:
    pattern:  /
    defaults: { _controller: AcmePaginationTestBundle:Default:index }
    options:
        expose: true

acme_pagination_test_list:
    pattern:  /list/
    defaults: { _controller: AcmePaginationTestBundle:Default:list }
