parameters:
#    acme_pagination_test.example.class: Acme\PaginationTestBundle\Example

services:
#    acme_pagination_test.example:
#        class: %acme_pagination_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
